name: Build Release
on:
  release:
    types: [published]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go build -ldflags "-X main.Version=${{ steps.semantic.outputs.new_release_git_tag }}"

      - name: Compress
        run: tar cfz collectd-redis_linux_x86_64.tar.gz collectd-redis

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: collectd-redis_linux_x86_64.tar.gz
          asset_name: collectd-redis_linux_x86_64.tar.gz
          asset_content_type: application/zip


