name: Build and release a version
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - name: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
        id: version
      - name: Set up 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build

      - name: binversion
        run: echo "::set-output name=binversion::$(./collectd-redis version)"
        id: binversion

      - name: Test Version
        run: test ${{ steps.binversion.outputs.binversion }} = ${{ steps.version.outputs.version }}

      - name: Compress
        run: gzip collectd-redis

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: collectd-redis.gz
          asset_name: collectd-redis.gz
          asset_content_type: application/zip
