name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: makandra/github-actions/precommit@main
